version: "3.4"
services:
  node-app:
    container_name: node-test
    image: ahmedghonimdev/node-test
    restart: always
    build:
      context: .
      target: prod
    ports:
      - 3005:3005
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    restart: always
    volumes:
      - mogngo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  # postgres:
  #   image: postgres
  #   restart: always
  #   volumes:
  #     - postgres-db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: example
  redis:
    image: redis
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - node-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mogngo-db:
  postgres-db:
